# Generated by Django 5.0.3 on 2024-03-10 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintonCourt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=512)),
                (
                    'booking_cost_per_hour',
                    models.DecimalField(decimal_places=2, max_digits=22),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'person_in_charge',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='operations.operationuserprofile',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FutsalCourt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=512)),
                (
                    'booking_cost_per_hour',
                    models.DecimalField(decimal_places=2, max_digits=22),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'person_in_charge',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='operations.operationuserprofile',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TennisCourt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=512)),
                (
                    'booking_cost_per_hour',
                    models.DecimalField(decimal_places=2, max_digits=22),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'person_in_charge',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='operations.operationuserprofile',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
