# Generated by Django 4.1.13 on 2024-03-11 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationUserProfile',
            new_name='OperationProfile',
        ),
    ]
