# Generated by Django 4.1.13 on 2024-03-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badmintoncourtbooking',
            old_name='facility',
            new_name='court',
        ),
        migrations.RenameField(
            model_name='futsalcourtbooking',
            old_name='facility',
            new_name='court',
        ),
        migrations.RenameField(
            model_name='tenniscourtbooking',
            old_name='facility',
            new_name='court',
        ),
    ]
